### PR TITLE
Add Julia Benchmark

### PR DESCRIPTION
**Pull request by freeboson**
[Julia](http://julialang.org) is a popular language for scientific computing. Here is an implementation of the benchmark in Julia. It is not a compiled language but the Makefile will install the dependencies. On my computer, the benchmark time normalized by the C benchmark was 1.05. (See below for details.)

Sample output:
```
$ julia -O3 leapfrog.jl
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11, 2.99907e-11, 2.62385e-12], [0.0161992, 3.99409, 0.349437]]
  2.240018 seconds (2.67 M allocations: 123.727 MiB, 13.01% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596, 0.000112353, 9.82963e-6], [-2.98638, 1.45884e7, 1.27632e6]]
181.466304 seconds (29.41 k allocations: 1.161 MiB)
```

The C benchmark:
```
$ time target/optimized/leapfrog
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221
target/optimized/leapfrog  172.69s user 0.14s system 99% cpu 2:53.39 total
```

Building the dependencies:
```
$ make
echo "Installing dependencies..."
Installing dependencies...
julia -e 'Pkg.add("StaticArrays"); using StaticArrays;'
INFO: Installing StaticArrays v0.3.0
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of StaticArrays
INFO: Use `Pkg.update()` to get the latest versions of your packages
echo "To run: julia -O3 leapfrog.jl"
To run: julia -O3 leapfrog.jl
```

### CODE REVIEW

**Comment by marblestation** [comment]
Cool! Thank you so much, Julia is a language that I had in mind but I never found the time to learn and implement this test with it.

**Comment by marblestation** [comment]
BTW @freeboson, in OSX, contrary to what your output shows, I'm getting times closer to Go than to C.

**Comment by freeboson** [comment]
Interesting. I'm not sure what could account for the difference (I am also on macOS). I used a Julia-0.6-pre (nightly) build, but I just checked with Julia-0.5 and got similar results (179.5s). Just to check, if you run the C benchmark right now, you still get 2m53s?

**Comment by marblestation** [comment]
I re-executed both:

```
c# time target/optimized/leapfrog
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221

real	3m1.400s
user	2m54.004s
sys	0m1.485s
```

```
julia# time target/optimized/leapfrog
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11,2.99907e-11,2.62385e-12],[0.0161992,3.99409,0.349437]]
  1.532618 seconds (1.02 M allocations: 42.344 MB, 3.86% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596,0.000112353,9.82963e-6],[-2.98638,1.45884e7,1.27632e6]]
241.651051 seconds (24.54 k allocations: 804.297 KB)

real	4m6.342s
user	4m0.141s
sys	0m1.729s
```

Where the 241.65 seconds correspond to 4m1.65s, so taking the output from the time command (4m0.141s) is a good enough approximation too (even if there is some compilation done at the beginning). In any case, closer to Go execution times.

I'm using gcc version 6.3.0 (MacPorts gcc6 6.3.0_1) and julia version 0.5.1 in MacBook Air (1,6 GHz Intel Core i5, 8 GB 1600 MHz DDR3) with macOS Sierra 10.12.3.

**Comment by sbromberger** [comment]
Hi,

Just as another data point (OSX, Julia 0.5.2):

```
seth@schroeder:~/tmp/benchmark-leapfrog/c$ time target/optimized/leapfrog
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221

real	2m49.375s
user	2m44.207s
sys	0m1.196s

seth@schroeder:~/tmp/benchmark-leapfrog/julia$ julia leapfrog.jl
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11,2.99907e-11,2.62385e-12],[0.0161992,3.99409,0.349437]]
  1.080151 seconds (1.02 M allocations: 42.401 MB, 4.87% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596,0.000112353,9.82963e-6],[-2.98638,1.45884e7,1.27632e6]]
173.828079 seconds (24.54 k allocations: 804.297 KB)

seth@schroeder:~/tmp/benchmark-leapfrog/julia$ time target/optimized/leapfrog
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11,2.99907e-11,2.62385e-12],[0.0161992,3.99409,0.349437]]
  0.994581 seconds (1.02 M allocations: 42.401 MB, 5.26% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596,0.000112353,9.82963e-6],[-2.98638,1.45884e7,1.27632e6]]
169.820611 seconds (24.54 k allocations: 804.297 KB)

real	2m51.761s
user	2m47.884s
sys	0m0.718s
```

**Comment by sbromberger** [comment]
On a 2.5GHz i5 mac mini:
```
seth@snoopy:~/tmp/benchmark-leapfrog/c$ time target/optimized/leapfrog
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221

real	3m27.770s
user	3m25.643s
sys	0m0.547s

seth@snoopy:~/tmp/benchmark-leapfrog/julia$ time target/optimized/leapfrog
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11,2.99907e-11,2.62385e-12],[0.0161992,3.99409,0.349437]]
  1.402482 seconds (1.02 M allocations: 42.529 MB, 6.03% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596,0.000112353,9.82963e-6],[-2.98638,1.45884e7,1.27632e6]]
222.743702 seconds (24.54 k allocations: 803.906 KB)

real	3m47.921s
user	3m47.724s
sys	0m0.552s
```

and after rebuild:
```
seth@snoopy:~/tmp/benchmark-leapfrog/julia$ julia -O3 leapfrog.jl
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11,2.99907e-11,2.62385e-12],[0.0161992,3.99409,0.349437]]
  1.533492 seconds (1.13 M allocations: 46.844 MB, 9.03% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596,0.000112353,9.82963e-6],[-2.98638,1.45884e7,1.27632e6]]
219.744964 seconds (24.54 k allocations: 803.906 KB)
```

**Comment by ChrisRackauckas** [comment]
I'm curious what could cause the difference. It should compile down to pretty much the same native code as C. 

@marblestation , did you install using the generic binaries? That would be one way to try and eliminate variance.

Maybe check the timing if using clang? See if the C code on the same compiler has this issue on that machine.

**Comment by staticfloat** [comment]
@marblestation Hi, I'm one of the Julia devs.  I was linked here because someone noticed this performance difference.  It's most likely because, if you downloaded a prebuilt version of Julia, the instructions that version of Julia uses are very conservative, (e.g. no SSE3+, no AVX, etc...) and therefore the calculations performed with Julia are much slower.

You can rebuild what is called the "system image" with the instruction set that is native to your CPU using the following commands within a Julia session:

```julia
include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))
build_sysimg(force=true)
```

This will take somewhere around two or three minutes to complete, as it recompiles the entire standard library of julia.  Once it's done, it should print out something along the lines of:
```
INFO: System image successfully built at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib
INFO: Julia will automatically load this system image at next startup
```

Then, just quit Julia, and run your script again to see if it's any faster.

**Comment by sbromberger** [comment]
@staticfloat @ChrisRackauckas - note that the second set of timings that I posted (from the mini) were using the version of Julia that came from `brew install`.

**Comment by ChrisRackauckas** [comment]
@freeboson mentioned in the Gitter that he just used the prebuilt nightly and prebuilt v0.5.1, so I don't think the issue is the system image. The problem is too small to SIMD well anyways.

**Comment by freeboson** [comment]
@staticfloat the performance that I reported is with the generic prebuilt nightly (and I get the same results with the 0.5 release). However, @marblestation is the only one to run the BM on ~1.6 GHz.

**Comment by marblestation** [comment]
@ChrisRackauckas I installed using the generic binaries from julia's website (the dmg file).

@staticfloat I followed your instructions, I got the same execution times:

```
INFO: Linking sys.dylib
ld: warning: object file (/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.o) was built for newer OSX version (13.4) than being linked (10.12)
INFO: System image successfully built at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib
INFO: Julia will automatically load this system image at next startup
```

```
julia# time target/optimized/leapfrog
Running up to tmax=10 to compile...
Positions:StaticArrays.SVector{3,Float64}[[3.07027e-11,2.99907e-11,2.62385e-12],[0.0161992,3.99409,0.349437]]
  1.517352 seconds (1.02 M allocations: 42.565 MB, 5.27% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596,0.000112353,9.82963e-6],[-2.98638,1.45884e7,1.27632e6]]
251.337667 seconds (24.54 k allocations: 803.906 KB)

real	4m17.684s
user	4m11.305s
sys	0m1.985s
```

Since for gcc I was using the macports one, I re-compiled with the gcc included in OSX (Apple LLVM version 8.0.0 - clang-800.0.42.1) and these are the results:

```
c# time target/optimized/leapfrog
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221

real	3m56.738s
user	3m49.142s
sys	0m1.745s
```

And with this compiler the execution time gets close to Go too for the C implementation, to summarize:

- Go: 4m10.233s
- Julia 0.5.1: 4m11.305s
- C (Apple LLVM version 8.0.0 - clang-800.0.42.1): 3m49.142s
- C (gcc - MacPorts gcc6 6.3.0_1): 2m54.004s

I'm surprised to see this difference between both C compilers. What C compiler is everybody else using? Could any of you try the Go version in your machines to have another point of reference?

Thanks!

**Comment by freeboson** [comment]
@marblestation I've run all benchmarks. Here are my results:

+ C (Apple LLVM version 8.0.0 (clang-800.0.42.1)): 171.04s
+ C (gcc-6 (Homebrew GCC 6.3.0_1) 6.3.0): 164.8s
+ Go: (go version go1.8 darwin/amd64): 192.78s
+ Rust: (rustc 1.16.0): 134.13s
+ Julia: (Version 0.6.0-pre.alpha.100 (2017-03-09 02:03 UTC)): 178.76s (183.13s incl. compile)

I am not able to reproduce the large variance in C compilers that you are seeing. Even if we leave all that alone, and look at the time normalized by *Rust*, we have a large difference. I am getting Julia/Rust = 1.33, while you are getting 1.64.

```
$ time c/target/optimized/leapfrog-apple_llvm
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221
c/target/optimized/leapfrog-apple_llvm  170.68s user 0.09s system 99% cpu 2:51.04 total
$ time c/target/optimized/leapfrog-gcc_6
Position 1: 0.000113 0.000112 0.000010 | Position 2: -2.986377 14588403.613911 1276320.032221
c/target/optimized/leapfrog-gcc_6  161.52s user 0.30s system 98% cpu 2:44.80 total
$ time go/target/optimized/leapfrog
Positions: &[[0.00011259641961937496 0.00011235312238407964 9.82962683070781e-06] [-2.986377308237493 1.4588403613911422e+07 1.2763200322206458e+06]]
go/target/optimized/leapfrog  190.39s user 0.33s system 98% cpu 3:12.78 total
$ time rust/target/optimized/leapfrog
[[0.00011259641961937496, 0.00011235312238407964, 0.00000982962683070781], [-2.986377308237493, 14588403.613911422, 1276320.0322206458]]
rust/target/optimized/leapfrog  133.29s user 0.12s system 99% cpu 2:14.13 total
$ time fortran/target/optimized/leapfrog
   1.1259641961937496E-004   1.1235312238407964E-004   9.8296268307078112E-006  -2.9863773082374929        14588403.613911422        1276320.0322206458
fortran/target/optimized/leapfrog  160.14s user 0.23s system 96% cpu 2:45.35 total
$ time julia/target/optimized/leapfrog
Running up to tmax=1.0 to compile...
WARNING: Base.LinearFast is deprecated, use Base.IndexLinear instead.
  likely near /Users/sujeeta/dev/benchmark-leapfrog/julia/leapfrog.jl:237
WARNING: Base.LinearFast is deprecated, use Base.IndexLinear instead.
  likely near /Users/sujeeta/dev/benchmark-leapfrog/julia/leapfrog.jl:237
WARNING: Base.LinearFast is deprecated, use Base.IndexLinear instead.
  likely near /Users/sujeeta/dev/benchmark-leapfrog/julia/leapfrog.jl:237
Positions:StaticArrays.SVector{3,Float64}[[1.96333e-13, 9.67771e-14, 8.4669e-15], [0.0162, 0.0383432, 0.0033546]]
  2.153412 seconds (2.67 M allocations: 123.556 MiB, 13.23% gc time)
Running full benchmark...
Positions:StaticArrays.SVector{3,Float64}[[0.000112596, 0.000112353, 9.82963e-6], [-2.98638, 1.45884e7, 1.27632e6]]
178.756471 seconds (29.42 k allocations: 1.161 MiB)
julia/target/optimized/leapfrog  182.60s user 0.33s system 99% cpu 3:03.13 total
```

**Comment by ChrisRackauckas** [comment]
So we never did find out why @marblestation 's LLVM doesn't seem to be applying all of the optimizations? Probably an old OS or something?

**Pull request merged**
